#!/bin/bash

# Color
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
GRAY='\033[0;37m'
GRAY2='\033[1;30m'
RED2='\033[1;31m'
GREEN2='\033[1;32m'
YELLOW='\033[1;33m'
BLUE2='\033[1;34m'
PURPLE2='\033[1;35m'
CYAN2='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Setup basic directory information
IDEA_DIRECTORY="${HOME}/.idea"
IDEA_GIT_DIRECTORY="${HOME}/.idea/.git"
LIFE_DIRECTORY="life"
WEEK_DIRECTORY="week"
MONTH_DIRECTORY="month"
YEAR_DIRECTORY="year"
DAILY_DIRECTORY="daily"

# options & arguments
OPTION=${1}
CATEGORY=${2}
ARGUMENT=${2}

# date & time
CURRENT_DATE=$(date "+%d-%m-%y")
CURRENT_TIME=$(date "+%H:%M:%S")
CURRENT_DATETIME=$(date "+%d-%m-%y|%H:%M:%S")

# Today variables
CURRENT_DATETIME_DIRECTORY=${IDEA_DIRECTORY}/$(date "+%d-%m-%y|%H:%M:%S")
CURRENT_DATE_DIRECTORY=${IDEA_DIRECTORY}/$(date "+%d-%m-%y")
CURRENT_TIME_FILE=${IDEA_DIRECTORY}/${CURRENT_DATE}/$(date "+%H:%M:%S")

function list {

	if [[ ! -d ${IDEA_DIRECTORY} ]]; then
		echo "Your ${IDEA_DIRECTORY} directory does not exist"
		echo "Exiting..."
		exit
		if [[ ! -d ${IDEA_GIT_DIRECTORY} ]]; then
			echo "Your ${IDEA_DIRECTORY} is not a git directory"
			echo "Exiting..."
			exit
		else
			IDEAS=$(ls ${CURRENT_DATE_DIRECTORY})
			echo "Today [${CURRENT_DATE}]"
			for IDEA in ${IDEAS}; do
				INDEX=1
				CONTENT=$(cat ${CURRENT_DATE_DIRECTORY}/${IDEA})
				echo "${INDEX} - [${IDEA}]: [${CONTENT}]"
				INDEX=$((${INDEX} + 1))
			done
		fi
	else
		IDEAS=$(ls ${CURRENT_DATE_DIRECTORY})
		echo "Today [${CURRENT_DATE}]"
		for IDEA in ${IDEAS}; do
			INDEX=1
			CONTENT=$(cat ${CURRENT_DATE_DIRECTORY}/${IDEA})
			echo "${INDEX} - [${IDEA}]: [${CONTENT}]"
			INDEX=$((${INDEX} + 1))
		done
	fi
}

function add {
	if [[ ! -d ${IDEA_DIRECTORY} ]]; then
		mkdir -p ${IDEA_DIRECTORY}
		if [[ ! -d ${IDEA_GIT_DIRECTORY} ]]; then
			git init -C ${IDEA_DIRECTORY}
		else

			echo "Please enter idea"
			read IDEA
			mkdir -p ${CURRENT_DATE_DIRECTORY}
			echo ${IDEA} >>${CURRENT_TIME_FILE}
			git -C ${IDEA_DIRECTORY} add ${CURRENT_TIME_FILE}
			git -C ${IDEA_DIRECTORY} commit -m "Add new idea @ ${CURRENT_DATETIME}"
		fi
	else
		echo "Please enter idea"
		read IDEA
		mkdir -p ${CURRENT_DATE_DIRECTORY}
		echo ${IDEA} >>${CURRENT_TIME_FILE}
		git -C ${IDEA_DIRECTORY} add ${CURRENT_TIME_FILE}
		git -C ${IDEA_DIRECTORY} commit -m "Add new idea @ ${CURRENT_DATETIME}"
	fi
}

function push {
	if [[ ! -d ${IDEA_DIRECTORY} ]]; then
		mkdir -p ${IDEA_DIRECTORY}
		if [[ ! -d ${IDEA_GIT_DIRECTORY} ]]; then
			git init -C ${IDEA_DIRECTORY}
		else

			git -C ${IDEA_DIRECTORY} push
		fi
	else
		git -C ${IDEA_DIRECTORY} push
	fi
}

function pull {
	if [[ ! -d ${IDEA_DIRECTORY} ]]; then
		mkdir -p ${IDEA_DIRECTORY}
		if [[ ! -d ${IDEA_GIT_DIRECTORY} ]]; then
			git init -C ${IDEA_DIRECTORY}
		else

			git -C ${IDEA_DIRECTORY} pull --rebase
		fi
	else
		git -C ${IDEA_DIRECTORY} pull --rebase
	fi
}

case ${OPTION} in
"add")
	echo "### [ADD NEW IDEA] ###"
	add
	;;
"list" | "Wednesday" | "Thursday")
	echo "### [LIST IDEAS] ###"
	list
	;;
"push")
	echo "### [PUSH IDEAS] ###"
	push
	;;
"pull")
	echo "### [PULL IDEAS] ###"
	pull
	;;
*)
	echo "Options guideline"
	echo "add: to add new idea"
	echo "list: to list today ideas"
	echo "push: to push ideas"
	echo "pull[rebase]: to pull ideas"
	;;
esac
