#!/bin/bash

LOCAL_IPADDRESS="localhost"
REMOTE_PORT=${1}
REMOTE_IPADDRESS=${2}
LOCAL_PORT=${3}
BASTION_HOST=${4}

ssh -NCq -L ${LOCAL_IPADDRESS}:${LOCAL_PORT}:${REMOTE_IPADDRESS}:${REMOTE_PORT} ${BASTION_HOST}
