#!/bin/bash

# Setup basic directory information
TODO_DIRECTORY="${HOME}/.todo"
LIFE_DIRECTORY="life"
WEEK_DIRECTORY="week"
MONTH_DIRECTORY="month"
YEAR_DIRECTORY="year"
DAILY_DIRECTORY="daily"

# Basic option
# add - add new task
# miss - list all missed tasks
# remain - list all remain tasks
# done - list all done tasks

# Basic argument
# --date [ specific date ]
# --range [ range date ]
# --category [ category of tasks ]

# Directory structure
# .todo
# ├── daily
# │     ├── 11-10-2004
# │     │   ├── first-company
# │     │   └── second-firm
# │     └── 12-10-2004
# │         ├── first-organization
# │         └── second-enterprise
# │
# ├── week
# ├── month
# ├── year
# └── life
