#!/bin/bash

# Color
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
GRAY='\033[0;37m'
GRAY2='\033[1;30m'
RED2='\033[1;31m'
GREEN2='\033[1;32m'
YELLOW='\033[1;33m'
BLUE2='\033[1;34m'
PURPLE2='\033[1;35m'
CYAN2='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Setup basic directory information
TODO_DIRECTORY="${HOME}/.todo"
LIFE_DIRECTORY="life"
WEEK_DIRECTORY="week"
MONTH_DIRECTORY="month"
YEAR_DIRECTORY="year"
DAILY_DIRECTORY="daily"

# options & arguments
OPTION=${1}
CATEGORY=${2}
ARGUMENT=${2}

# date & time
CURRENT_DATE=$(date "+%d-%m-%y")
CURRENT_TIME=$(date "+%H:%M:%S")
CURRENT_DATETIME=$(date "+%d-%m-%y|%H:%M:%S")

# Basic option
# add - add new task
# list - list all tasks
# miss - list all missed tasks
# remain - list all remain tasks
# done - list all done tasks

# Basic argument
# --date [ specific date ]
# --range [ range date ]
# --category [ category of tasks ]

# Directory structure
# .todo
# ├── daily
# │     ├── 11-10-2004
# │     │   ├── notitle
# │     │   ├── first-company
# │     │   └── second-firm
# │     └── 12-10-2004
# │         ├── notitle
# │         ├── first-organization
# │         └── second-enterprise
# │
# ├── week
# ├── month
# ├── year
# └── life

# Deadline type
# Never
# Unknown yet
# specific date [ 30-10-2024 ]
# range from current date [ 2w ]

# file description
# yaml
# task name
# description
# detail action [ user write ]
# deadline
# done or not

# functions
function add {

	local CATEGORY=${1}
	local DATE=${2}
	local GROUP=${3}

	if [[ ${CATEGORY} == "daily" ]]; then

		mkdir -p ${TODO_DIRECTORY}/${DAILY_DIRECTORY}/${CURRENT_DATE}

		read -p "$(echo -e "Enter name [${GREEN2}name${NC}]: ")" NAME
		NAME=${NAME:-name}
		read -p "$(echo -e "Enter description [${GREEN2}description${NC}]: ")" DESCRIPTION
		DESCRIPTION=${DESCRIPTION:-notitle}
		read -p "$(echo -e "Enter detail [${GREEN2}detail${NC}]: ")" DETAIL
		DETAIL=${DETAIL:-notitle}
		read -p "$(echo -e "Enter deadline [${GREEN2}1w${NC}]: ")" DEADLINE
		DEADLINE=${DEADLINE:-1w}

		if [[ -z ${GROUP} ]]; then
			GROUP="notitle"
			YAML=$(
				cat <<EOT
- name: ${NAME}
  description: ${DESCRIPTION}
  detail: ${DETAIL}
  deadline: ${DEADLINE}
  complete: false

EOT
			)
			echo "${YAML}" >>"${TODO_DIRECTORY}/${DAILY_DIRECTORY}/${CURRENT_DATE}/${GROUP}.yaml"
		fi
	fi

}

function list {
	local CATEGORY=${1}
	local DATE=${2}
	local GROUP=${3}

	if [[ ${CATEGORY} == "daily" ]]; then

		if [[ -z ${GROUP} ]]; then
			GROUP="notitle"
			cat "${TODO_DIRECTORY}/${DAILY_DIRECTORY}/${CURRENT_DATE}/${GROUP}.yaml" | yq -r '.[].name'
		fi
	fi
}



if [[ ${OPTION} == "add" ]]; then
	add ${CATEGORY} ${CURRENT_DATE} ${GROUP}
elif [[ ${OPTION} == "list" ]]; then
	list ${CATEGORY} ${CURRENT_DATE} ${GROUP}
fi
