#!/bin/bash

# Setup basic directory information
TODO_DIRECTORY="${HOME}/.todo"
LIFE_DIRECTORY="life"
WEEK_DIRECTORY="week"
MONTH_DIRECTORY="month"
YEAR_DIRECTORY="year"
DAILY_DIRECTORY="daily"

# options & arguments
OPTION=${1}
ARGUMENT=${2}

# date & time
CURRENT_DATE=$(date "+%d-%m-%y")
CURRENT_TIME=$(date "+%H:%M:%S")
CURRENT_DATETIME=$(date "+%d-%m-%y|%H:%M:%S")

# Basic option
# add - add new task
# list - list all tasks
# miss - list all missed tasks
# remain - list all remain tasks
# done - list all done tasks

# Basic argument
# --date [ specific date ]
# --range [ range date ]
# --category [ category of tasks ]

# Directory structure
# .todo
# ├── daily
# │     ├── 11-10-2004
# │     │   ├── notitle
# │     │   ├── first-company
# │     │   └── second-firm
# │     └── 12-10-2004
# │         ├── notitle
# │         ├── first-organization
# │         └── second-enterprise
# │
# ├── week
# ├── month
# ├── year
# └── life

# Deadline type
# Never
# specific date [ 30-10-2024 ]
# range from current date [ 2w ]

# functions
function add {
	local CATEGORY=${1}
	local DATE=${2}
	local GROUP=${3}

	if [[ ${CATEGORY} == "daily" ]]; then
		mkdir -p ${TODO_DIRECTORY}/${DAILY_DIRECTORY}/${DATE}
		if [[ -z ${GROUP} ]]; then
			GROUP="notitle"
		fi
	fi
}
