export ow="-owide"
export oy="-oyaml"
export sba="--sort-by=metadata.creationTimestamp"
export sbst="--sort-by=status.phase"
export sbna="--sort-by=metadata.name"
export sbno="--sort-by=spec.nodeName"
export shc="--show-managed-fields=false"
export shl="--show-labels"
export b6="base64"
export b6d="base64 --decode"
export osu="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
export hh="export HISTFILE=/dev/null && unset SSH_CONNECTION SSH_CLIENT"
export clr="--color"
export lkf="-lock=false"
export pr="--profile"
export pr1="--profile hqd"
export pr2="--profile dat@notional"
export pr4="--profile devops_readonly@aeronet"
export bsp="--break-system-packages"
export tlf="-lock=fasle"
