#!/bin/bash

code --install-extension 4ops.terraform
code --install-extension aldijav.golangwithdidi
code --install-extension bradlc.vscode-tailwindcss
code --install-extension catppuccin.catppuccin-vsc
code --install-extension chaitanyashahare.lazygit
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension honnamkuan.golang-snippets
code --install-extension marlon407.code-groovy
code --install-extension mellowmarshmallow.groovy
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension neonxp.gotools
code --install-extension nhoizey.gremlins
code --install-extension nicolasvuillamy.vscode-groovy-lint
code --install-extension omkarbhede.tailwindcss-tune
code --install-extension premparihar.gotestexplorer
code --install-extension quicktype.quicktype
code --install-extension redhat.vscode-yaml
code --install-extension tabnine.tabnine-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension zxh404.vscode-proto3
