### User specific aliases and functions
alias rm='rm -f'
alias cp='cp -rf'
alias mv='mv -f'

### Tmux command
alias tml='tmux ls'
alias tma='tmux attach -t'
alias tmr='tmux rename-session -t'
alias tmn='tmux new -s'
alias tmk='tmux kill-session -t'
alias tms='tmux source ~/.tmux.conf'

### Screen command
alias scr='screen'
alias scrl='screen -ls'
alias scrd='screen -d'
alias scrr='screen -r'
alias viscr='vi ~/.screenrc'

### Emacs command
alias em='emacs'
alias emq='emacs -q'
alias emel='emacs -q ~/init.el'

### Linux command
alias mn='cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo'
alias ps11='export PS1="\e[0;33m\u\e[0m\e[0;32m@\h\e[0m \e[1;32m \w \n \$ \e[0m"'
alias ps12='export PS1="\u@\H >"  \u: haquocdat, \H: aws, @: $'
alias upn='plug ; yg ; yn ; cm ; sn'
alias upu='. ~/preconfig/Suitcase/bash/commands/copySuitcase.sh'
alias ups='plug ; yn ; gceh ; gcnh ; cm ; sn ; ed400 ; up2 ; rv ; up3 ; rtm'
alias upss='plug ; yn ; gceh ; gcnh ; cm ; sn ; ed400 ; up2 ; rv ; up3 ; rtm ; invim ; ipip ; ipynvim ; plug2 ; up5 ; rnv '
alias upsss='plug ; yn ; gceh ; gcnh ; cm ; sn ; ed400 ; up2 ; rv ; up3 ; rtm ; invim ; ipip ; ipynvim ; plug2 ; up5 ; rnv ; up6 ; swl'
alias iness='yterra ; ydk ; se docker ; ss docker ; ymagh ; yi gh ; iglab ; ilg'
alias upi='upsss ; iness'
alias doom='git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs ; ~/.config/emacs/bin/doom install'
alias spacemacs='git clone https://github.com/syl20bnr/spacemacs $HOME/.emacs.d'
alias proj='nigv ; vue create frontend ; cd frontend ; axios ; md src/services ; md src/routes ; mv src/components/HelloWorld.vue src/components/winners.vue ; touch src/routes/index.js ; touch src/services/Api.js ; touch src/services/winners.js ; cd - ; md server ; md server/src ; md server/src/models ; md server/src/routes ; cd server ; touch src/app.js ; touch src/models/winners.js ; touch src/routes/winners.js ; npmi ; mevn ; cd -'
alias proj2='nigv ; vue create frontend ; cd frontend ; axios ; md src/services ; md src/routes ; mv src/components/HelloWorld.vue src/components/winners.vue ; touch src/routes/index.js ; touch src/services/Api.js ; touch src/services/winners.js ; cd - ; md server ; md server/src ; md server/src/models ; md server/src/routes ; cd server ; touch src/app.js ; touch src/models/winners.js ; touch src/routes/winners.js ; npmi ; pevn ; cd -'
alias m='make'
alias vuecf='vue create frontend'
alias virm='vi README.md'
alias vimc='vi main.c'
alias ll='ls -la'
alias lr='ll ~'
alias lll='ll /'
alias ldkimg='ll /var/lib/docker/overlay2'
alias loop='. ~/preconfig/Suitcase/bash/commands/loopShell.sh'
alias llg='. ~/preconfig/Suitcase/bash/commands/llg.sh'
alias llgc='. ~/preconfig/Suitcase/bash/commands/llgc.sh'
alias lp='netstat -lnp'
alias fk='fuser -k'
alias lbk='ll ~/preconfig/backup'
alias cdl='cd /'
alias cdcm='cd ~/Suitcase/bash/commands'
alias cddoc='cd ~/Suitcase/bash/docs'
alias cdsb='cd ~/Suitcase/bash'
alias cdcn='cd ~/.config/nvim'
alias cdp='cd ~/preconfig'
alias cdps='cd ~/preconfig/Suitcase'
alias cdpr='cd /proc'
alias lpr='ls -la /proc'
alias cdsn='cd ~/Suitcase/snippets'
alias cdw='cd ~/Suitcase/windows'
alias lh='ll /home'
alias cdh='cd /home'
alias cdb='cd /bin'
alias cdbin='cd /usr/local/bin'
alias letc='ll /etc'
alias cdetc='cd /etc'
alias cdpcfg='cd ~/preconfig'
alias lbin='ll /usr/local/bin'
alias lgob='ll ~/go/bin'
alias lrp='ll /etc/yum.repos.d'
alias cdrp='cd /etc/yum.repos.d'
alias md='mkdir'
alias rf='rm -rf'
alias rfa='rm -rf *'
alias rfaa='rm -rf * .*'
alias rm='rm -f'
alias rma='rm -f *'
alias rmaa='rm -f * *.'
alias tarx='tar -xvzf'
alias hoi='hostname -i'
alias hos='hostname -s'
alias hs='hostnamectl status'
alias exp='openssl x509 -noout -text -in'
alias etcdbk='ECTDCTL_API=3 etcdctl'
alias histf='export HISTTIMEFORMAT="%F %T "'
alias hi='history'
alias psx='ps aux'
alias dhis='rm ~/.bash_history'
alias hz='hi | tail -n 10'
alias h2='hi | tail -n 20'
alias cl='clear'
alias cb='cd -' 
alias cq='cd ..' 
alias cq2='cd ../..' 
alias cq3='cd ../../..' 
alias ..='cd ..'
alias ...='cd ../..'
alias .4='cd ../../..'
alias .5='cd ../../../..'
alias .6='cd ../../../../..'
alias vi="vi"
alias vnv="vi ~/.config/nvim/init.vim"
alias vil="vi ~/.config/nvim/init.lua"
alias vilk="vi ~/Suitcase/bash/link.txt"
alias plug2="sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'"
alias plug="curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
alias packernvim="git clone --depth 1 https://github.com/wbthomason/packer.nvim  ~/.local/share/nvim/site/pack/packer/start/packer.nvim"
alias plugin2='git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim'
alias plugin='git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim'
alias cob='ll | wc'
alias aw='. ~/preconfig/Suitcase/bash/commands/awk.sh'
alias eag='. ~/preconfig/Suitcase/bash/commands/eag.sh'
alias ag='ag --hidden'
alias virclc='vi /etc/rc.local'
alias viz='vi ~/.zshrc'
alias val='vi ~/.bashrc'
alias vgdb='vi ~/.gdbinit'
alias vlk='vi ~/Suitcase/bash/link.txt'
alias vac='vi ~/Suitcase/windows/alias.cmd'
alias vws='vi ~/Suitcase/windows/setup.bat'
alias vicp='vi ./docker-compose.yaml'
alias vigr2='vi /etc/grub2.cfg'
alias vij2='vi ./*.j2'
alias vigig='vi ./.gitignore'
alias vihig='vi ./.helmignore'
alias vihr='vi ./redis-values.yaml'
alias vidig='vi ./.dockerignore'
alias vikub='vi ~/.kube/config'
alias vigcf='vi ./.gitconfig'
alias vicf='vi ./configure'
alias vicfac='vi ./configure.ac'
alias vim4='vi ./aclocal.m4'
alias vimkt='vi ./Makefile.tpl'
alias vimka='vi ./Makefile.am'
alias vimki='vi ./Makefile.in'
alias vidk='vi ./Dockerfile'
alias vijk='vi ./Jenkinsfile'
alias vitv='vi ./.travis.yml'
alias vicc='vi .circleci/config.yml'
alias vigf='vi ./Gemfile'
alias vigfl='vi ./Gemfile.lock'
alias vipf='vi ./Pipfile'
alias vipfl='vi ./Pipfile.lock'
alias vimk='vi ./Makefile'
alias vibs='vi ./buildspec.yml'
alias vias='vi ./appspec.yml'
alias vbbk='vi ~/preconfig/backup/.bashrc.backup'
alias vvbk='vi ~/preconfig/backup/.vimrc.backup'
alias vtbk='vi ~/preconfig/backup/.tmux.conf.backup'
alias vrc='vi ~/.vimrc'
alias vtm='vi ~/.tmux.conf'
alias viy='vi *.yaml'
alias vish='vi *.sh'
alias viwf='vi ./.github/workflows/*'
alias viwfb='vi ./.github/workflows/build.yml'
alias vigl='vi .gitlab-ci.yml'
alias viinv='vi inventory'
alias vee='vi ~/init.el'
alias va='vi ~/Suitcase/bash/.bashrc'
alias vipj='vi package.json'
alias vdel='vi delete.sh'
alias vdel2='vi delete2.sh'
alias vdel3='vi delete3.sh'
alias vvc='vi ~/Suitcase/bash/.vimrc'
alias vnc='vi ~/Suitcase/bash/init.vim'
alias vtc='vi ~/Suitcase/bash/.tmux.conf'
alias swl='.  ~/preconfig/Suitcase/bash/commands/switch.sh'
alias vlc='vi ~/Suitcase/bash/init.lua'
alias vec='vi init.el'
alias vrcu='vi ~/preconfig/.vimrc'
alias vrco='vi ~/preconfig/previmrc'
alias vtmu='vi ~/preconfig/.tmux.conf'
alias vtmo='vi ~/preconfig/pretmux'
alias veeu='vi ~/preconfig/init.el'
alias veeo='vi ~/preconfig/preinitel'
alias viid='vi ~/.ssh/id_ed25519'
alias visshcf='vi ~/.ssh/config'
alias virsapu='vi ~/.ssh/id_rsa.pu'
alias virsapr='vi ~/.ssh/id_rsa'
alias vrsa='vi ~/.ssh/id_rsa'
alias viah='vi /etc/ansible/hosts'
alias viacf='vi /etc/ansible/ansible.cfg'
alias vi8='vi *'
alias visu='vi /etc/sudoers'
alias vitab='vi /etc/fstab'
alias vilim='vi /etc/security/limits.conf'
alias visys='vi /etc/sysctl.conf'
alias asudo='. ~/preconfig/Suitcase/bash/commands/addSudoers.sh'
alias vissh='vi /etc/ssh/sshd_config'
alias ssha='eval $(ssh-agent) && ssh-add'
alias vmc='vi ./main.c'
alias vimt='vi main.tf'
alias vimx='vi main.tex'
alias viva='vi variables.tf'
alias ed400='c400 ~/.ssh/id_ed25519'
alias eb='exec bash'
alias catjk='sudo cat /var/lib/jenkins/secrets/initialAdminPassword'
alias catr64='cat ~/.docker/config.json | base64'
alias cos='cat /etc/os-release'
alias catak='cat ~/.ssh/authorized_keys'
alias rsapr='cat ~/.ssh/id_rsa'
alias rsapu='cat ~/.ssh/id_rsa.pub'
alias cpass='cat /etc/passwd'
alias lssh='ll /root/.ssh'
alias rn='route -n'
alias ir='ip route'
alias ex='exit'
alias 25519del='rm -f  ~/.ssh/id_ed25519*'
alias 25519gen='ssh-keygen -t ed25519 -C'
alias 25519pu='cat ~/.ssh/id_ed25519.pub'
alias 25519pr='cat ~/.ssh/id_ed25519'
alias kgrsa='ssh-keygen -t rsa'
alias kgrsa4='ssh-keygen -t rsa -b 4096'
alias diffbin='. ~/preconfig/Suitcase/bash/commands/diffBinary.sh'
alias vdbin='. ~/preconfig/Suitcase/bash/commands/binVimdiff.sh'
alias sshci='. ~/preconfig/Suitcase/bash/commands/sshCopyId.sh'
alias sshcia='. ~/preconfig/Suitcase/bash/commands/sshCopyIdAuthentication.sh'
alias rv='. ~/preconfig/run.sh'
alias rnv='. ~/preconfig/nvim.sh'
alias rnl='. ~/preconfig/lua.sh'
alias rtm='. ~/preconfig/tmux.sh'
alias rem='. ~/preconfig/emacs.sh'
alias sn='. ~/preconfig/commands/snippets.sh'
alias rr='. ~/.bashrc'
alias rdh='readelf -h'
alias rdl='readelf -l'
alias objh='objdump -h'
alias b0='cp -f ~/.bashrc ~/.bashrc~'
alias b1='rm ~/.bashrc'
alias b2='cp -f  ~/.bashrc~ ~/.bashrc'
alias cdssh='cd ~/.ssh'
alias c400='chmod 400'
alias c200='chmod 200'
alias c300='chmod 300'
alias c600='chmod 600'
alias c700='chmod 700'
alias c500='chmod 500'
alias c100='chmod 100'
alias c644='chmod 644'
alias c777='chmod 777'
alias upz='bash <(curl -s https://raw.githubusercontent.com/haquocdat543/Suitcase/main/bash/zsh.sh )'
alias up1='bash <(curl -s https://raw.githubusercontent.com/haquocdat543/Suitcase/main/bash/alias.sh )'
alias up2='. ~/preconfig/Suitcase/bash/vimconfig.sh'
alias up3='. ~/preconfig/Suitcase/bash/tmuxconfig.sh'
alias up4='. ~/preconfig/Suitcase/bash/emacsconfig.sh'
alias up5='. ~/preconfig/Suitcase/bash/nvimconfig.sh'
alias up6='. ~/preconfig/Suitcase/bash/luaconfig.sh'
alias s6s='swl ; up6 ; swl'
alias dall='bash <(curl -s https://raw.githubusercontent.com/haquocdat543/Suitcase/main/bash/delete.sh)'
alias dall2='bash <(curl -s https://raw.githubusercontent.com/haquocdat543/Suitcase/main/bash/delete2.sh)'
alias dall3='bash <(curl -s https://raw.githubusercontent.com/haquocdat543/Suitcase/main/bash/delete3.sh)'
alias k8smu='. ~/preconfig/Suitcase/bash/master-ubuntu.sh'
alias k8smc='. ~/preconfig/Suitcase/bash/master-centos.sh'
alias k8swu='. ~/preconfig/Suitcase/bash/worker-ubuntu.sh'
alias k8swc='. ~/preconfig/Suitcase/bash/worker-centos.sh'
alias mnode='. ~/preconfig/Suitcase/bash/k8s-ami.sh'


### Documentation
alias dock8s='vi -m ~/preconfig/Suitcase/bash/docs/dock8s.md'
alias docgcc='vi -m ~/preconfig/Suitcase/bash/docs/gcc.md'
alias dochelm='vi -m ~/preconfig/Suitcase/bash/docs/dochelm.md'
alias docsql='vi -m ~/preconfig/Suitcase/bash/docs/docsql.md'
alias docfzf='vi -m ~/preconfig/Suitcase/bash/docs/fzf.md'
alias docbash='vi -m ~/preconfig/Suitcase/bash/docs/bash.md'
alias docans='vi -m ~/preconfig/Suitcase/bash/docs/ansible.md'

### Installation
alias igo='. ~/preconfig/Suitcase/bash/commands/goInstall.sh'
alias ifzf='. ~/preconfig/Suitcase/bash/commands/fzfInstall.sh'
alias ieksctl='. ~/preconfig/Suitcase/bash/commands/eksctlInstall.sh'
alias ikubectl='. ~/preconfig/Suitcase/bash/commands/kubectlInstall.sh'
alias ilg='. ~/preconfig/Suitcase/bash/commands/lazygit.sh'
alias ilk='. ~/preconfig/Suitcase/bash/commands/lazykubernetes.sh'
alias ild='. ~/preconfig/Suitcase/bash/commands/lazydocker.sh'
alias ik9s='. ~/preconfig/Suitcase/bash/commands/k9s.sh'
alias iag='. ~/preconfig/Suitcase/bash/commands/agInstall.sh'
alias invim='. ~/preconfig/Suitcase/bash/commands/nvimInstall.sh'
alias ipip='cd ; wget https://bootstrap.pypa.io/get-pip.py ; python3 get-pip.py ; cb'
alias ipynvim='python3 -m pip install --upgrade pynvim'
alias ikubectl='. ~/preconfig/Suitcase/bash/commands/kubectl.sh'
alias ikub='. ~/preconfig/Suitcase/bash/commands/kubectl.sh'
alias irg='. ~/preconfig/Suitcase/bash/commands/ripgrep.sh'
alias ibrew='/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
alias icargo='curl https://sh.rustup.rs -sSf | sh ; source "\$HOME/.cargo/env"'
alias ia4='curl -L https://aka.ms/InstallAzureCli | bash'
alias ig2='. ~/preconfig/Suitcase/bash/commands/gcpCli.sh'
alias icabal='. ~/preconfig/Suitcase/bash/commands/cabalInstall.sh'
alias ikustomize='. ~/preconfig/Suitcase/bash/commands/kustomizeInstall.sh'
alias ikus='. ~/preconfig/Suitcase/bash/commands/kustomizeInstall.sh'
alias irustup="curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
alias iosmosis='curl -sL https://get.osmosis.zone/install > i.py && python3 i.py'
alias invm='curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash ; up1'
alias igaiad='. ~/preconfig/Suitcase/bash/commands/gaiaInstall.sh'
alias icccli='. ~/preconfig/Suitcase/bash/commands/circleCliInstall.sh'
alias iredisfs='. ~/preconfig/Suitcase/bash/commands/redisInstallFromSource.sh'
alias ikom='. ~/preconfig/Suitcase/bash/commands/komposeInstall.sh'
alias ipulumi='. ~/preconfig/Suitcase/bash/commands/pulumiInstall.sh'
alias igrype='. ~/preconfig/Suitcase/bash/commands/grypeInstall.sh'
alias idelta='. ~/preconfig/Suitcase/bash/commands/deltaInstall.sh'
alias ijenkins='. ~/preconfig/Suitcase/bash/commands/jenkinInstall.sh'
alias imysql='. ~/preconfig/Suitcase/bash/commands/amzLinuxMysql.sh'
alias ikar='. ~/preconfig/Suitcase/bash/commands/ikubectlArgoRollouts.sh'
alias iglab='. ~/preconfig/Suitcase/bash/commands/gitlabCliInstall.sh'
alias ipacker='. ~/preconfig/Suitcase/bash/commands/packerInstall.sh'
alias ivault='. ~/preconfig/Suitcase/bash/commands/vaultInstall.sh'
alias iconsul='. ~/preconfig/Suitcase/bash/commands/consulInstall.sh'
alias ietcd='. ~/preconfig/Suitcase/bash/commands/etcdInstall.sh'
alias ipsql='. ~/preconfig/Suitcase/bash/commands/postgresInstall.sh'
alias itrivy='rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.rpm'
alias gettrivy='. ~/preconfig/Suitcase/bash/commands/trivyGet.sh'
alias unistio='. ~/preconfig/Suitcase/bash/commands/istioInstall.sh'
alias iistio='. ~/preconfig/Suitcase/bash/commands/istioInstall.sh'
alias iargocd='. ~/preconfig/Suitcase/bash/commands/argoCDInstall.sh'
alias iteleinflux='. ~/preconfig/Suitcase/bash/commands/teleInfluxInstall.sh'
alias igrafana='. ~/preconfig/Suitcase/bash/commands/grafanaInstall.sh'
alias igra='. ~/preconfig/Suitcase/bash/commands/grafanaInstall.sh'
alias isonarqube='. ~/preconfig/Suitcase/bash/commands/sonarqubeInstall.sh'
alias isonar='. ~/preconfig/Suitcase/bash/commands/sonarqubeInstall.sh'
alias yzsh='yum install -y zsh'
alias iohmyzsh='sudo curl -L http://install.ohmyz.sh | sh'
alias izellij='. ~/preconfig/Suitcase/bash/commands/zellijInstall.sh'
alias ihelm='. ~/preconfig/Suitcase/bash/commands/helmInstall.sh'
alias ikitty='curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin'
alias o1='cd ; git clone https://github.com/gpakosz/.tmux.git ; ln -s -f .tmux/.tmux.conf ; cp .tmux/.tmux.conf.local .'
alias idk='yd ; sd ; ed'

alias lg='lazygit'
alias ldk='lazydocker'
alias lk='lazykubernetes'
alias lnpm='lazynpm'
alias lcli='lazycli'

### AWS command
alias a2c='aws configure'
alias a2cl='aws configure list'
alias a2ec2ti='aws ec2 terminate-instances --instance-ids'
alias a2ec2tic='aws ec2 terminate-instances --instance-ids $(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId]' --filters Name=instance-state-name,Values=running --output text)'
alias a2ec2sic='aws ec2 stop-instances --instance-ids $(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId]' --filters Name=instance-state-name,Values=running --output text)'
alias a2ec2li='aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId]' --filters Name=instance-state-name,Values=running --output text'
alias a2ec2di='aws ec2 describe-instances'
alias a2ec2leni='aws ec2 describe-network-interfaces'
alias a2ec2deni='aws ec2 delete-network-interface --network-interface-id'
alias a2ec2desi='aws ec2 describe-images'
alias a2ec2dri='aws ec2 deregister-image --image-id'
alias a2ec2dsi='aws ec2 disable-image --image-id'
alias a2s3lb='aws s3api list-buckets'
alias a2s3cb='aws s3api create-bucket --bucket'
alias a2s3db='aws s3api delete-bucket --bucket'
alias a2clmd='. ~/preconfig/Suitcase/bash/commands/clmDeploy.sh'
alias a2clmu='. ~/preconfig/Suitcase/bash/commands/clmUpdate.sh'
alias a2clmdcap='. ~/preconfig/Suitcase/bash/commands/clmDeployCapability.sh'
alias a2clmds='aws cloudformation delete-stack --stack-name'
alias a2clmdd='aws cloudformation delete-stack --stack-name default'
alias a2clmli='aws cloudformation describe-stacks'
alias a2clmo='aws cloudformation describe-stacks --query Stacks[].Outputs[*].[OutputKey,OutputValue] --output text'
alias a2eksuk='aws eks update-kubeconfig --name'
alias a2rdsci='. ~/preconfig/Suitcase/bash/commands/rds.sh'
alias a2rdsdi='aws rds delete-db-instance --db-instance-identifier'
alias a2rdsli='aws rds describe-db-instances'
alias a2rdslii='aws rds describe-db-instances | grep DBInstanceIdentifier'
alias a2eccc='. ~/preconfig/Suitcase/bash/commands/elasticache.sh'
alias a2ecli='aws elasticache describe-cache-clusters'
alias a2ecdc='aws elasticache delete-cache-cluster --cache-cluster-id'
alias a2iamlr='aws iam list-roles'
alias a2iamlp='aws iam list-policies'
alias a2iamls='aws iam list-users'
alias a2iamlg='aws iam list-groups'
alias a2elbdes='aws elb describe-load-balancers'
alias a2elbdl='aws elb delete-load-balancer --load-balancer-name'
alias a2lmdi='. ~/preconfig/Suitcase/bash/commands/lambdaInvoke.sh'
alias a2lmdlf='aws lambda list-functions'
alias a2lmddf='aws lambda delete-function --function-name'
alias a2apigks='aws apigateway get-api-keys'
alias a2apigk='aws apigateway get-api-key --api-key'
alias a2ddblt='aws dynamodb list-tables'
alias a2ddbdt='aws dynamodb delete-table --table-name'
alias a2ccmlr='aws codecommit list-repositories'
alias a2ccmcr='aws codecommit create-repository --repository-name'
alias a2ccmdr='aws codecommit delete-repository --repository-name'
alias a2cblp='aws codebuild list-projects'
alias a2cbdp='aws codebuild delete-project --project-name'
alias a2cbsb='aws codebuild start-build --project-name'
alias a2cdla='aws codedeploy list-applications'
alias a2cdld='aws codedeploy list-deployments'
alias a2cdcd='aws codedeploy create-deployment --application-name'
alias a2cdda='aws codedeploy delete-application --application-name'
alias a2cpllp='aws codepipeline list-pipelines'
alias a2cpllp='aws codepipeline create-pipeline --pipeline'
alias a2cpldp='aws codepipeline delete-pipeline --name'
alias a2ecrcr='aws ecr create-repository --repository-name'
alias a2ecrdr='aws ecr delete-repository --repository-name'
alias a2ecrlr='aws ecr describe-repositories'
alias a2iamlk='aws iam list-ssh-public-keys'
alias a2iamulk='. ~/preconfig/Suitcase/bash/commands/iamUploadKey.sh'
alias a2iamdk='. ~/preconfig/Suitcase/bash/commands/iamDeleteKey.sh'
alias a2dnmlt='aws dynamodb list-tables'
alias a2deseps='aws ec2 describe-vpc-endpoint-services'
alias a2desep='aws ec2 describe-vpc-endpoints'
alias a2qlll='aws qldb list-ledgers'
alias a2qldl='aws qldb delete-ledger --name'
alias a2qldesl='aws qldb describe-ledger --name'
alias a2gci='aws sts get-caller-identity'
alias a2gci2='aws account get-contact-information'

### Gitlab command
alias glal='glab auth login'
alias glrl='glab repo list'
alias glrc='glab repo create'
alias glrcl='glab repo clone'
alias glrd='glab repo delete'
alias glvs='glab variable set'
alias glvd='glab variable delete'
alias glvl='glab variable list'
alias glvu='glab variable update'

### Github command
alias ghal='gh auth login'
alias ghrcl='gh repo clone'
alias ghsa='gh ssh-key add'
alias ghrl='gh repo list'
alias ghrr='gh repo rename'
alias ghrc='gh repo create'
alias ghrd='gh repo delete' # You must inside to that repo
alias ghev='gh repo edit --visibility' # You must inside to that repo
alias ghevpu='gh repo edit --visibility public' # You must inside to that repo
alias ghevpr='gh repo edit --visibility private' # You must inside to that repo
alias ghrv='gh repo view'
alias ghre='gh repo edit'
alias ghss='gh secret set'
alias ghsl='gh secret list'
alias ghsl='gh secret list'
alias ghsde='gh secret delete -e'
alias ghsd='gh secret delete'
alias ghwl='gh workflow list'
alias ghwv='gh workflow view'
alias ghrr='gh repo rename'

### Git command

alias vd='vimdiff'
alias gd='git diff'
alias gds='git diff --staged'
alias gi='git init'
alias gcl='git clone'
alias gcls='. ~/preconfig/Suitcase/bash/commands/githubSshClone.sh'
alias gclh='. ~/preconfig/Suitcase/bash/commands/githubHttpClone.sh'
alias gcld='git clone --depth 1'
alias gT='git clone git@github.com:haquocdat543/Terraform.git ~/Terraform'
alias gS='git clone git@github.com:haquocdat543/Suitcase.git ~/Suitcase'
alias gA='git clone git@github.com:haquocdat543/ArgoCD.git ~/ArgoCD'
alias gL='git clone https://github.com/arismelachroinos/lscript.git ~/lscript'
alias gN='git clone https://github.com/Elteoremadebeethoven/nvim-config.git'
alias gnn='rm -rf ~/.config/nvim ; git clone https://github.com/Elteoremadebeethoven/nvim-config.git ~/.config/nvim'
alias cdgh='cd $(git rev-parse --show-toplevel)/.git/hooks'
alias cdgr='cd $(git rev-parse --show-toplevel)'
alias gcfa='. ~/preconfig/Suitcase/bash/commands/gitAddAlias.sh'
alias gc='git commit -m'
alias gC='git commit -a'
alias gcu='git commit -m "Update"'
alias gt='git tag'
alias gta='git tag -a'
alias gtd='git tag -d'
## if you want to push all tags to repo use: git push <remote> <branch> --tags
## if you want to delete all tags to repo use: git push --delete <remote> <branch> --tags && git tag -d --tags
alias gs='git status'
alias ga='git add'
alias ga.='git add .'
alias gai='git add --ignore-removal .'
alias gaa='git add -A'
alias gap='git add --patch'
alias gac='gaa ; gc'
alias gau='git add -u'
alias gcp='git cherry-pick'
alias g1='git reset --soft HEAD~1'
alias g0='git reset --hard HEAD~1'
alias g2='git reset --'
alias g2a='git reset -- .'
alias g3='git restore --'
alias g4='git restore --source=HEAD'
alias g4a='git restore --source=HEAD .'
alias g5='git restore --source='
alias grv='git revert'
alias g6='git revert HEAD'
alias gct='git rev-list --count'
alias gca='git rev-list --count --all'
alias gch='git rev-list HEAD --count'
alias gco='git count-objects'
alias gcov='git count-objects -v'
alias gb='git branch'
alias gba='git branch -a'
alias gbm='git branch -M'
alias gbr='git branch move'
alias gbd='git branch -D'
alias gbis='git bisect start'
alias gbig='git bisect good'
alias gbib='git bisect bad'
alias gbir='git bisect reset'
alias gsw='git switch'
alias gcb='git checkout -b'
alias gck='git checkout'
alias gckm='git checkout main'
alias gckm2='git checkout master'
alias gckd='git checkout dev'
alias gckn='. ~/preconfig/Suitcase/bash/commands/gckNumber.sh'
alias gcknm='. ~/preconfig/Suitcase/bash/commands/gckNumberMerge.sh'
alias gck1='git checkout `git rev-list --max-parents=0 HEAD | tail -n 1`'
alias gm='git merge'
alias grb='git rebase'
alias gsq='git rebase -i'
alias gl='git log'
alias glo='git log --oneline'
alias glo10='git log -n 10 --oneline'
alias gl10='git log -n 10'
alias glog='git log --oneline --graph'
alias glop="git log --graph --abbrev-commit --decorate --color --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%ai%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%n'"
alias gp='git push'
alias gpu='git push -u'
alias gpod='git push origin --delete'
alias gpom='git push origin main'
alias gpomf='git push origin main -f'
alias scpkube='. ~/preconfig/Suitcase/bash/commands/scpkube.sh'
alias scpssh='. ~/preconfig/Suitcase/bash/commands/scpssh.sh'
alias cpb='. ~/preconfig/Suitcase/bash/commands/copyToBinDir.sh'
alias cproot='. ~/preconfig/Suitcase/bash/commands/copyroot.sh'
alias gall='. ~/preconfig/Suitcase/bash/gitconfig/gitPushOriginMain.sh'
alias cmd='. ~/preconfig/Suitcase/bash/commands/cmd.sh'
alias doc='. ~/preconfig/Suitcase/bash/commands/doc.sh'
alias cnt='. ~/preconfig/Suitcase/bash/commands/connect.sh'
alias nven='. ~/preconfig/Suitcase/bash/vimconfig/nvimen.sh'
alias ven='. ~/preconfig/Suitcase/bash/vimconfig/vimen.sh'
alias gr='git remote'
alias gpl='git pull'
alias gplom='git pull origin main'
alias grp='git request-pull'
alias gf='git fetch'
alias gra='git remote add'
alias gsl='git stash list'
alias gss='git stash save'
alias gsa='git stash apply'
alias gsd='git stash drop'
alias gssh='git stash show'
alias gwa='git worktree add'
alias gwl='git worktree list'
alias gwp='git worktree prune'
alias gsma='git submodule add'
alias gsmu='git submodule update'
alias grm='git rm'
alias gcn='git config --global user.name'
alias gce='git config --global user.email'
alias gcprt='git config pull.rebase true'
alias gcprf='git config pull.rebase false'
alias gcpfo='git config pull.ff only'
alias gcnh='git config --global user.name "haquocdat543"'
alias gceh='git config --global user.email "wwwdatha543@gmail.com"'

### Ansible command
alias a1='ansible'
alias a1a='ansible all'
alias a1alh='ansible all --list-hosts'
alias a1p='ansible-playbook'
alias a1plt='ansible-playbook --list-tags'
alias a1pi='ansible-playbook -i'
alias a1cf='ansible-config'
alias a1cs='ansible-console'
alias an='ansible'
alias ana='ansible all'
alias anl='ansible-lint'
alias analh='ansible all --list-hosts'
alias anp='ansible-playbook'
alias anpc='ansible-playbook --check'
alias anplt='ansible-playbook --list-tags'
alias anpi='ansible-playbook -i'
alias anpp='. ~/preconfig/Suitcase/bash/commands/ansiblePlaybookInventory.sh'
alias ancf='ansible-config'
alias ancs='ansible-console'
alias angin='ansible-galaxy init'
alias ang='ansible-galaxy'
alias angci='ansible-galaxy collection install'
alias angcl='ansible-galaxy collection list'
alias angis='ansible-galaxy install'
alias angisrp='ansible-galaxy install --roles-path'
alias angl='ansible-galaxy list'
alias angrl='ansible-galaxy role list'
alias angrs='. ~/preconfig/Suitcase/bash/commands/galaxyRoleSearch.sh'
alias angri='. ~/preconfig/Suitcase/bash/commands/roleInfo.sh'
alias angrm='ansible-galaxy remove'
alias ancfi='ansible-config init --disabled > ansible.cfg'
alias ancfit='ansible-config init --disabled -t all > ansible.cfg'
alias anve='ansible-vault encrypt'

### Vagrant command
alias vgi='vagrant init'
alias vgu='vagrant up'
alias vgd='vagrant destroy'
alias vgss='vagrant ssh'
alias vgsc='vagrant ssh-config'
alias vgs='vagrant status'

### Pulumi command
alias plmlg='pulumi login'
alias plmn='pulumi new'
alias plmnawsts='pulumi new aws-typescript'
alias plmnawsjs='pulumi new aws-javascript'
alias plmnawspy='pulumi new aws-python'
alias plmnawsgo='pulumi new aws-go'
alias plmnawscs='pulumi new aws-csharp'
alias plmu='pulumi up'
alias plmus='pulumi up -s'
alias plms='pulumi stack'
alias plmsi='pulumi stack init'
alias plmsl='pulumi stack ls'
alias plmsrm='pulumi stack rm'
alias plmsl='pulumi stack select'
alias plmsi='pulumi stack init'
alias plmd='pulumi destroy'
alias plmds='pulumi destroy -s'
alias plmcs='pulumi config set'

### Packer command
alias pki='packer init'
alias pkb='packer build'
alias pkbc='packer build .'
alias pkbv='packer build -var'
alias pkpi='packer plugins install'
alias pkpia='packer plugins install github.com/hashicorp/amazon'

### Terraform command
alias tfc='. ~/preconfig/Suitcase/bash/commands/clean.sh'
alias tfi='terraform init'
alias tfs='terraform show'
alias tfp='terraform plan'
alias tfim='terraform import'
alias tflg='terraform login'
alias tfr='terraform refresh'
alias tfro='terraform apply -refresh-only'
alias tfa='terraform apply'
alias tfd='terraform deploy'
alias tfwl='terraform workspace list'
alias tfws='terraform workspace select'
alias tfwn='terraform workspace new'
alias tfaa='terraform apply --auto-approve'
alias tfda='terraform destroy --auto-approve'
alias tfia='tfi ; tfaa'
alias tfdia='tfda ; tfi ; tfaa'

### Docker command

alias dk='docker'
alias dki='docker init'
alias dcp='docker-compose'
alias dcpud='docker-compose up -d'
alias dcpd='docker-compose down'
alias dcps='docker-compose ps'
alias dcpl='docker-compose logs'
alias dcpb='docker-compose build'
alias dcps='docker-compose stop'
alias dcpt='docker-compose top'
alias dcprs='docker-compose restart'
alias dcpe='docker-compose exec'
alias dcppl='docker-compose pull'
alias dl='docker logs'
alias dlg='docker login'
alias dnl='docker network ls'
alias dni='docker network inspect'
alias dno='docker network inspect'
alias dnc='docker network create'
alias dncd='docker network create --driver'
alias dncn='docker network connect'
alias dncnip='docker network connect --ip'
alias dndcn='docker network disconnect'
alias dpsn='docker ps -a -q'
alias dps='docker ps -a'
alias dc='docker commit'
alias dkcp='docker cp'
alias dload='docker load -i'
alias dsave='docker save --output'
alias dtop='docker top'
alias dvl='docker volume ls'
alias dvi='docker volume inspect'
alias dvc='docker volume create'
alias dvr='docker volume rm'
alias dr='docker run'
alias drit='docker run -it'
alias dritrm='docker run -it --rm'
alias dvch='. ~/preconfig/Suitcase/bash/commands/dockerHostMount.sh'
alias dritm='. ~/preconfig/Suitcase/bash/commands/dockerMount.sh'
alias dvf='. ~/preconfig/Suitcase/bash/commands/dockerVolumeFrom.sh'
alias dki='docker inspect'
alias dkif='docker info'
alias ddiff='docker diff'
alias dstat='docker stats'
alias dstop='docker stop'
alias dpo='docker port'
alias da='docker attach'
alias de='docker exec -it'
alias drm='docker rm -f'
alias dms='docker images'
alias dmsh='docker images history'
alias dmr='docker image rm'
alias dmp='docker image prune'
alias dpl='docker pull'
alias ds='docker search'
alias dnls='docker node ls'
alias dsps='docker service ps'
alias dsl='docker service ls'
alias dstl='docker stack ls'
alias dsc='docker service create'
alias dsr='docker service rm'
alias dsu='docker service update'
alias dstd='docker stack deploy -c'
alias dstdcp='docker stack deploy -c docker-compose.yaml'
alias dstr='docker stack rm'
alias db='docker build -f Dockerfile . -t'
alias dbplf='. ~/preconfig/Suitcase/bash/commands/dockerBuildPlatform.sh'
alias dt='docker tag'
alias dlg='docker login'
alias dp='docker push'
alias dmc='docker-machine'
alias dmcc='docker-machine create' #driver=?(virtualbox, vmware, hyperv) virtualMachineName
alias dmcl='docker-machine ls'
alias dmcst='docker-machine status'
alias dmcstt='docker-machine start'
alias dmcrst='docker-machine restart'
alias dmcstp='docker-machine stop'
alias dmcrm='docker-machine rm'
alias dmcip='docker-machine ip'
alias dmcscp='docker-machine scp -r'
alias dmcssh='docker-machine ssh'
alias dswi='docker swarm init --advertise-addr='
alias djm='docker swarm join-token manager'
alias djw='docker swarm join-token worker'

### Kubectl command
alias oidc='. ~/preconfig/Suitcase/bash/commands/oidc.sh'
alias expkub='. ~/preconfig/Suitcase/bash/commands/exportKubeConfig.sh'
alias k='kubectl'
alias kp='kubectl proxy'
alias kpf='kubectl port-forward' #<pod-name> <pod-port:host-port>
alias kl='kubectl label'
alias ks='kubectl scale'
alias kc='kubectl create'
alias kcns='kubectl create namespace'
alias kdns='kubectl delete namespace'
alias kcsi='. ~/preconfig/Suitcase/bash/commands/imagePullSecret.sh'
alias ktn='kubectl taint node'
alias kco='kubectl cordon'
alias kuco='kubectl uncordon'
alias kdrain='kubectl drain'
alias kgt='kubectl describe node | grep Taint'
alias krsd='kubectl rollout status deploy'
alias krhd='kubectl rollout history deploy'
alias krud='kubectl rollout undo deployment'
alias kga='kubectl get all'
alias kgan='kubectl get all -n'
alias des='describe'
alias de='delete'
alias km='kubeadm'
alias kmtc='kubeadm token create'
alias kmjw='kubeadm token create --print-join-command'
alias kmcp='. ~/preconfig/Suitcase/bash/controlplaneCertificate/controlplaneCertificate.sh'
alias kmuc='kubeadm init phase upload-certs --upload-certs'
alias kx='kubectl exec -it'
alias kq='kubectl describe quota'
alias kgp='kubectl get pod'
alias kgn='kubectl get node'
alias kgs='kubectl get svc'
alias kgd='kubectl get deploy'
alias kgcm='kubectl get configmap'
alias kgrc='kubectl get rc'
alias kgrs='kubectl get rs'
alias kgsts='kubectl get sts'
alias kgds='kubectl get ds'
alias kgsc='kubectl get secret'
alias kgc='kubectl get storageclasses'
alias kgpv='kubectl get pv'
alias kgpvc='kubectl get pvc'
alias kgr='kubectl get role'
alias kgrb='kubectl get rolebindings'
alias kgcr='kubectl get clusterroles'
alias kgcb='kubectl get clusterrolebindings'
alias kgi='kubectl get ingress'
alias kgr='kubectl get role'
alias kgnp='kubectl get networkpolicies'
alias kgsa='kubectl get serviceaccount'
alias kgpsp='kubectl get podsecuritypolicies'

alias kdesp='kubectl describe pod'
alias kdesn='kubectl describe node'
alias kdess='kubectl describe svc'
alias kdesd='kubectl describe deploy'
alias kdescm='kubectl describe configmap'
alias kdesrc='kubectl describe rc'
alias kdesrs='kubectl describe rs'
alias kdessts='kubectl describe sts'
alias kdesds='kubectl describe ds'
alias kdessc='kubectl describe secret'
alias kdesc='kubectl describe storageclasses'
alias kdespv='kubectl describe pv'
alias kdespvc='kubectl describe pvc'
alias kdesr='kubectl describe role'
alias kdesrb='kubectl describe rolebindings'
alias kdescr='kubectl describe clusterroles'
alias kdescb='kubectl describe clusterrolebindings'
alias kdesi='kubectl describe ingress'
alias kdesr='kubectl describe role'
alias kdesnp='kubectl describe networkpolicies'
alias kdessa='kubectl describe serviceaccount'
alias kdespsp='kubectl describe podsecuritypolicies'

alias kdp='kubectl delete pod'
alias kdn='kubectl delete node'
alias kds='kubectl delete svc'
alias kdd='kubectl delete deploy'
alias kdcm='kubectl delete configmap'
alias kdrc='kubectl delete rc'
alias kdrs='kubectl delete rs'
alias kdsts='kubectl delete sts'
alias kdds='kubectl delete ds'
alias kdsc='kubectl delete secret'
alias kdc='kubectl delete storageclasses'
alias kdpv='kubectl delete pv'
alias kdpvc='kubectl delete pvc'
alias kdr='kubectl delete role'
alias kdrb='kubectl delete rolebindings'
alias kdcr='kubectl delete clusterroles'
alias kdcb='kubectl delete clusterrolebindings'
alias kdi='kubectl delete ingress'
alias kdr='kubectl delete role'
alias kdnp='kubectl delete networkpolicies'
alias kdsa='kubectl delete serviceaccount'
alias kdpsp='kubectl delete podsecuritypolicy'

alias kpsci='. ~/preconfig/Suitcase/bash/servicePatch/clusterIP.sh'
alias kpslb='. ~/preconfig/Suitcase/bash/servicePatch/loadBalancer.sh'
alias kpsnp='. ~/preconfig/Suitcase/bash/servicePatch/nodePort.sh'
alias kpp='kubectl patch pod'
alias kpn='kubectl patch node'
alias kps='kubectl patch svc'
alias kpd='kubectl patch deploy'
alias kpcm='kubectl patch configmap'
alias kprc='kubectl patch rc'
alias kprs='kubectl patch rs'
alias kpsts='kubectl patch sts'
alias kpds='kubectl patch ds'
alias kpsc='kubectl patch secret'
alias kpc='kubectl patch storageclasses'
alias kppv='kubectl patch pv'
alias kppvc='kubectl patch pvc'
alias kpr='kubectl patch role'
alias kprb='kubectl patch rolebindings'
alias kpcr='kubectl patch clusterroles'
alias kpcb='kubectl patch clusterrolebindings'
alias kpi='kubectl patch ingress'
alias kpr='kubectl patch role'
alias kpnp='kubectl patch networkpolicies'
alias kpsa='kubectl patch serviceaccount'
alias kppsp='kubectl patch podsecuritypolicy'

alias kep='kubectl edit pod'
alias ken='kubectl edit node'
alias kes='kubectl edit svc'
alias ked='kubectl edit deploy'
alias kecm='kubectl edit configmap'
alias kerc='kubectl edit rc'
alias kers='kubectl edit rs'
alias kests='kubectl edit sts'
alias keds='kubectl edit ds'
alias kesc='kubectl edit secret'
alias kec='kubectl edit storageclass'
alias kepv='kubectl edit pv'
alias kepvc='kubectl edit pvc'
alias ker='kubectl edit role'
alias kerb='kubectl edit rolebindings'
alias kecr='kubectl edit clusterroles'
alias kecb='kubectl edit clusterrolebindings'
alias kei='kubectl edit ingress'
alias ker='kubectl edit role'
alias kenp='kubectl edit networkpolicy'
alias kesa='kubectl edit serviceaccount'
alias kepsp='kubectl edit podsecuritypolicy'

alias kge='kubectl get event'
alias ktn='kubectl taint node'

alias klg='kubectl logs'
alias kn='kubectl config set-context --current --namespace'
alias kgns='kubectl get namespace'
alias kgcc='cat ~/.kube/config | grep current | sed -e "s/current-context: //"'
alias kgcn='kubectl config view --minify -o jsonpath="{..namespace}"'
alias kgct='kubectl config get-contexts'
alias kr='kubectl run --dry-run=client -oyaml --image'
alias ka='kubectl apply -f'
alias kd='kubectl delete -f'
alias kgp='kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo'
alias krrd="kubectl run --namespace default my-redis-client --rm --tty -i --restart='Never' --image docker.io/bitnami/redis:6.2.1-debian-10-r0 -- bash"
# redis-cli -h my-redis -p 6379

### Link command
alias lns='ln -s'
alias lnfs='ln -f -s'

### Kustomization command
alias mdkz='md base ; md overlays'
alias vikz='vi ./kustomization.yaml'
alias kzi='kustomize init'
alias kzb='kustomize build'
alias kzbc='kustomize build .'
alias kze='kustomize edit'
alias kzcfg='kustomize cfg'
alias kzcr='kustomize create'
alias kzcp='kustomize complete'
alias kzfn='kustomize fn'

### Helm command
alias vicy='vi ./Chart.yaml'
alias hmcr='helm create'
alias hmra='helm repo add'
alias hmrs='helm repo search'
alias hmrastb='helm repo add stable https://charts.helm.sh/stable '
alias hmrabnm='helm repo add bitnami https://charts.bitnami.com/bitnami'
alias hmrapr='helm repo add prom https://prometheus-community.github.io/helm-charts'
alias hmrl='helm repo list'
alias hmru='helm repo update'
alias hmiv='. ~/preconfig/Suitcase/bash/commands/helmInstallValues.sh'
alias hmtpt='. ~/preconfig/Suitcase/bash/commands/helmTemplateTest.sh'
alias hmtt='helm test'
alias hmtp='helm template'
alias hmp='helm pull'
alias hms='helm show'
alias hmd='helm delete'
alias hmdi='helm diff'
alias hmi='helm install'
alias hmui='helm uninstall'
alias hmdep='helm dependency'
alias hmenv='helm env'
alias hmg='helm get'
alias hmhi='helm history'
alias hmpl='helm plugin'
alias hmpll='helm plugin list'
alias hmplun='helm plugin uninstall'
alias hmplud='helm plugin update'
alias hmpli='helm plugin install'
alias hmpk='helm package'
alias hmlt='helm lint'
alias hml='helm list'
alias hmla='helm list --all-namespaces'
alias hmrb='helm rollback'
alias hmu='helm upgrade'
alias hiels='helm repo add elastic https://helm.elastic.co ; helm install elasticsearch elastic/elasticsearch'
alias hifb='helm repo add elastic https://helm.elastic.co ; helm install filebeat elastic/filebeat'
alias hikb='helm repo add elastic https://helm.elastic.co ; helm install kibana elastic/kibana'
alias hilt='helm repo add elastic https://helm.elastic.co ; helm install logstash elastic/logstash'
alias himb='helm repo add elastic https://helm.elastic.co ; helm repo add prometheus-community https://prometheus-community.github.io/helm-charts ; helm install metricbeat elastic/metricbeat'
alias hird='helm install redis-cache bitnami/redis -f redis-values.yaml'

### Trivy command
alias t1='trivy'
alias t1i='trivy image'
alias t1r='trivy repo'
alias t1fs='trivy fs'
alias t1c='trivy client'
alias t1s='trivy server'
alias t1k='trivy k8s'
alias tv='trivy'
alias tvi='trivy image'
alias tvr='trivy repo'
alias tvfs='trivy fs'
alias tvc='trivy client'
alias tvs='trivy server'
alias tvk='trivy k8s'

### nasm  command
alias nf64='nasm -felf64'
alias cpl='. ~/preconfig/Suitcase/bash/commands/cpl.sh'
### Cron command
alias cre='crontab -e'
alias crl='crontab -l'
alias crr='crontab -r'
alias ycron='ycr ; secr ; sscr'

### Pip command
alias pi='pip install'
alias pians='pip install ansible'
alias pipyg='pip install pygments'

### brew command
alias bi='brew install'

### Go command
alias gor='go run'
alias gom='go mod'
alias gomv='go mod vendor'
alias gomi='go mod init'
alias gomt='go mod tidy'
alias gob='go build'
alias gobo='go build -o'
alias goe='go env'
alias goep='go env GOPATH'
alias goi='go install'
alias gog='go get'
alias goa='. ~/preconfig/Suitcase/bash/commands/goa.sh'

### gem command
alias gemi='gem install'
alias gemitv='gem install travis'

### circlecli command
alias ccc='circlecli'

### redis command
alias rds='redis-server'
alias rdc='redis-cli'
alias rdb='redis-benchmark'
alias rdcn='. ~/preconfig/Suitcase/bash/commands/redisConnect.sh'
alias rdcnp='. ~/preconfig/Suitcase/bash/commands/redisConnectPassword.sh'

### cargo command
alias gccv='gcc --version'
alias gcce='gcc -E'
alias gccs='gcc -S'
alias gccc='gcc -c'
alias gcco='gcc -o'

### cargo command
alias cga='cargo add'
alias cgn='cargo new'
alias cgb='cargo build'
alias cgr='cargo run'
alias cgrc='cargo run --'
alias cgbc='cargo build --'
alias vicgt='vi Cargo.toml'
alias vicgl='vi Cargo.lock'
alias virs='vi *.rs'

### Nginx commanda
alias n4v='nginx -V'
alias n4rl='nginx -s reload'
alias n4rs='nginx -s restart'
alias n4c='nginx -c'

### Make and automake
alias mj='sudo make -j'
alias mb='sudo make build'
alias mi='sudo make install'
alias atm='automake'
alias atc='autoconf'
alias atg='autogen'
alias atmam='automake --add-missing'
alias rcf='./configure'
alias rcfb='./configure --prefix=/usr/local/bin'
alias rcfbd='./configure --prefix=/usr/local/bin --disable-multilib'

### user and group
alias ua='useradd'
alias pw='passwd'

### gaiad cosmos
alias gaiai='gaiad init'
alias gaias='gaiad start'
alias gaiae='gaiad export'
alias g4i='gaiad init'
alias g4s='gaiad start'
alias g4e='gaiad export'

### GPG key
alias gpglk='gpg --list-keys'
alias gpgfgk='gpg --full-generate-key'
alias gpgpw='gpg --passwd'
alias gpgim='gpg --import'

### Other command
alias sqlcn='. ~/preconfig/Suitcase/bash/commands/sqlConnect.sh'
alias duh='sudo df -H'
alias fdl='sudo fdisk -l'
alias fdd='sudo fdisk'
alias lbk='lsblk'
alias lid='blkid'
alias fm4='sudo mkfs -t ext4'
alias mta='sudo mount -a'
alias umt='sudo umount'
alias mnt='sudo mount'
alias setmem1='sysctl -w vm.max_map_count=524288'
alias setmem2='sysctl -w fs.file=266000'
alias hdc='hexdump -C'
alias pf="fzf ${FZF_CTRL_T_OPTS}"
alias fzz='filepath=$(pf) ; vi $filepath'
alias fz='cd $(find . -type d -print | fzf)'
alias fzl='cd $(find . -type d -print | fzf) ; ll'
alias fzc='filepath=$(fzf) ; cp $filepath'
alias fzcc='filepath=$(fzf) ; cp $filepath .'
alias fzm='filepath=$(fzf) ; mv $filepath'
alias fzmm='filepath=$(fzf) ; mv $filepath .'
alias fzr='filepath=$(fzf) ; rm $filepath'
alias fzrf='filepath=$(fzf) ; rf $filepath'
alias dot='. ~/preconfig/Suitcase/bash/commands/dot.sh'
alias addas='. ~/preconfig/Suitcase/bash/commands/addAutoSuggest.sh'
alias addzsh='. ~/preconfig/Suitcase/bash/commands/addZshSource.sh'
alias setzsh='chsh -s $(which zsh)'
alias setbash='chsh -s $(which bash)'
alias s1='sudo su -'
alias s2='su - ec2-user'
alias s3='su - ubuntu'
alias s4='su -'
alias s5='su - postgres'
alias s6='su - sonar'
alias yi='yum install -y'
alias ni='npm install'
alias nr='npm run'
alias nigy='npm install -g yarn'
alias nigv='ni -g @vue/cli'
alias yagav='yarn global add @vue/cli'
alias npmi='npm init -y'
alias mevn='npm install express mongoose body-parser cors --save'
alias pevn='npm install express pg body-parser cors --save'
alias axios='npm install axios --save'
alias npms='npm start'
alias npman='npm add -D nodemon'
alias npmnm='nodemon app.js'
alias yas='yarn serve'
alias yab='yarn build'
alias nrs='npm run serve'
alias nrb='npm run build'
alias yacc='yarn cache clean -f'
alias ncc='npm cache clean -f'
alias rfya='rm -rf node-modules package-lock.json'
alias yarnall='yacc && rfya && yarn && yas'
alias npmall='ncc && rfya && ni && nrs'
alias yu='yum update -y'
alias ai='apt install -y'
alias au='apt update -y'
alias se='systemctl enable'
alias ss='systemctl start'
alias srs='systemctl restart'
alias sst='systemctl status'
alias sd='systemctl disable'
alias jctlprm='journalctl -u prometheus -f --no-pager'
alias secr='systemctl enable crond'
alias sscr='systemctl start crond'
alias yyu='yi yum-utils'
alias ymat='yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo'
alias ymagh='yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo'
alias yma='yum-config-manager --add-repo'
alias yme='yum-config-manager --enable'
alias darp='dnf config-manager --add-repo'
alias ynv='yum install -y neovim'
alias yt='yum install terraform -y'
alias yterra='yyu;ymat;yt'
alias ytm='yum install tmux -y'
alias ydbg='yum install dbg -y'
alias ycr='yum install cronie -y'
alias ydk='yum install docker -y'
alias ylz4='yum install lz4 -y'
alias yem='yum install emacs -y'
alias yd='yum install docker -y'
alias ylib2='sudo dnf -y install ninja-build cmake gcc make unzip gettext curl'
alias ylib='yum -y install pkgconfig automake gcc zlib-devel pcre-devel xz-devel'
alias ytool='yum -y groupinstall "Development Tools"'
alias yn='yum install nodejs -y'
alias ynpm='yum install npm -y' 
alias yg='yum install git -y'
alias yr='yum remove -y'
alias yu='yum update -y'
alias ygi='yum groupinstall -y'
alias ygr='yum groupremove -y'
alias ygu='yum groupupdate -y'
alias ygcc='yi gcc'
alias chx='sudo chmod +x'
alias ymaria='yum install -y mariadb105'
alias ydkcp='idc ; chxdc'
alias chxdc='sudo chmod +x /usr/local/bin/docker-compose'
alias idc='sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
